name: Reflections from Cyberia. Notizen für eine Kritik der politischen Technologie
markdown: redcarpet
pygments: true
description: "Notizen für eine Kritik der politischen Technologie"
url: "reflectionsfromcyberia.github.io"
permalink: /posts/:title
